/** Structured upgrade plan text returned by the Edge Function (AI or mock). */
export type UpgradePlanPayload = {
  upgradeSummary: string;
  businessOutcome: string;
  budgetRange: string;
  suggestedMaterials: string[];
  priorityChecklist: string[];
  contractorNotes: string;
  riskNotes: string[];
  photoPrepTips: string[];
};

export type PlanSource = 'ai' | 'mock';

export type AiProvider = 'gemini' | 'groq' | 'mock';

export function planSourceLabel(planSource?: PlanSource): string {
  return planSource === 'ai' ? 'AI-generated plan' : 'Template plan — AI unavailable';
}

export function planSourcePdfLabel(planSource?: PlanSource): string {
  return planSource === 'ai'
    ? 'Generated by SpaceFlip Pro AI'
    : 'Template planning draft — AI unavailable';
}

export function aiProviderDevLabel(provider?: AiProvider): string | undefined {
  if (!provider || provider === 'mock') return undefined;
  if (provider === 'gemini') return 'Gemini';
  if (provider === 'groq') return 'Groq';
  return undefined;
}
